name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: checkout submodules
        uses: textbook/git-checkout-submodule-action@master

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: syoboi-calendar-grpc-server
          username: chao
          password: hoge
          registry: docker.chao.tokyo

      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: |
            if docker ps | grep -q 'syoboi-calendar-grpc-server'; then docker rm -f syoboi-calendar-grpc-server; fi
            docker pull docker.chao.tokyo/syoboi-calendar-grpc-server:latest
            docker run --name syoboi-calendar-grpc-server -p 10001:50051 -d docker.chao.tokyo/syoboi-calendar-grpc-server:latest
