name: deploy

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: syoboi-calendar-grpc-server
          username: chao
          password: hoge
          registry: docker.chao.tokyo

      - name: send docker-compose.yml to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          source: docker-compose.yml
          target: /home/chao/src/chao.tokyo/services/syoboi-calendar-grpc-server
      
      - name: deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: docker-compose -f /home/chao/src/chao.tokyo/services/syoboi-calendar-grpc-server/docker-compose.yml up -d
